services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_API_WS_URL: ${NEXT_PUBLIC_API_WS_URL}
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID:-}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        NEXT_PUBLIC_GOOGLE_PROJECT_ID: ${NEXT_PUBLIC_GOOGLE_PROJECT_ID}
    env_file:
      - .env
    ports:
      - "5173:3000"
    restart: unless-stopped